# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: theory.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='theory.proto',
  package='theory',
  syntax='proto3',
  serialized_pb=_b('\n\x0ctheory.proto\x12\x06theory\x1a\x1bgoogle/protobuf/empty.proto\"4\n\x05UiReq\x12\x0e\n\x06\x61\x63tion\x18\x01 \x01(\t\x12\x0b\n\x03val\x18\x02 \x01(\t\x12\x0e\n\x06userId\x18\x03 \x01(\t\")\n\nReactorReq\x12\x0e\n\x06\x61\x63tion\x18\x01 \x01(\t\x12\x0b\n\x03val\x18\x02 \x01(\t\"3\n\rReactorReqArr\x12\"\n\x06reqLst\x18\x01 \x03(\x0b\x32\x12.theory.ReactorReq\"&\n\x04UiId\x12\n\n\x02id\x18\x01 \x01(\t\x12\x12\n\nadapterLst\x18\x02 \x03(\t\"?\n\tFieldData\x12\r\n\x05\x63mdId\x18\x01 \x01(\x05\x12\x11\n\tfieldName\x18\x02 \x01(\t\x12\x10\n\x08jsonData\x18\x03 \x01(\t\"?\n\x0b\x43mdFxnInput\x12\r\n\x05\x63mdId\x18\x01 \x01(\x05\x12\x0f\n\x07\x66xnName\x18\x02 \x01(\t\x12\x10\n\x08jsonData\x18\x03 \x01(\t\"@\n\x0euiData4Adapter\x12\x1c\n\x14\x61\x64\x61pterBufferModelId\x18\x01 \x01(\x05\x12\x10\n\x08jsonData\x18\x02 \x01(\t\"\x1c\n\x08JsonData\x12\x10\n\x08jsonData\x18\x01 \x01(\t\"G\n\x0cModelLstData\x12\x0f\n\x07\x61ppName\x18\x01 \x01(\t\x12\x11\n\tmodelName\x18\x02 \x01(\t\x12\x13\n\x0bjsonDataLst\x18\x03 \x03(\t\"\x07\n\x05\x45mpty2\x89\x03\n\x07Reactor\x12.\n\x03\x62ye\x12\r.theory.Empty\x1a\x16.google.protobuf.Empty\"\x00\x12.\n\x04\x63\x61ll\x12\r.theory.UiReq\x1a\x15.theory.ReactorReqArr\"\x00\x12\x31\n\x08register\x12\x0c.theory.UiId\x1a\x15.theory.ReactorReqArr\"\x00\x12\x35\n\x0csyncFormData\x12\x11.theory.FieldData\x1a\x10.theory.JsonData\"\x00\x12\x38\n\rcallCmdSubFxn\x12\x13.theory.CmdFxnInput\x1a\x10.theory.JsonData\"\x00\x12\x39\n\x0b\x61\x64\x61ptFromUi\x12\x16.theory.uiData4Adapter\x1a\x10.theory.JsonData\"\x00\x12?\n\x0eupsertModelLst\x12\x14.theory.ModelLstData\x1a\x15.theory.ReactorReqArr\"\x00\x62\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])




_UIREQ = _descriptor.Descriptor(
  name='UiReq',
  full_name='theory.UiReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='action', full_name='theory.UiReq.action', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='val', full_name='theory.UiReq.val', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='userId', full_name='theory.UiReq.userId', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=53,
  serialized_end=105,
)


_REACTORREQ = _descriptor.Descriptor(
  name='ReactorReq',
  full_name='theory.ReactorReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='action', full_name='theory.ReactorReq.action', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='val', full_name='theory.ReactorReq.val', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=107,
  serialized_end=148,
)


_REACTORREQARR = _descriptor.Descriptor(
  name='ReactorReqArr',
  full_name='theory.ReactorReqArr',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='reqLst', full_name='theory.ReactorReqArr.reqLst', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=150,
  serialized_end=201,
)


_UIID = _descriptor.Descriptor(
  name='UiId',
  full_name='theory.UiId',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='theory.UiId.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='adapterLst', full_name='theory.UiId.adapterLst', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=203,
  serialized_end=241,
)


_FIELDDATA = _descriptor.Descriptor(
  name='FieldData',
  full_name='theory.FieldData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cmdId', full_name='theory.FieldData.cmdId', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='fieldName', full_name='theory.FieldData.fieldName', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='jsonData', full_name='theory.FieldData.jsonData', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=243,
  serialized_end=306,
)


_CMDFXNINPUT = _descriptor.Descriptor(
  name='CmdFxnInput',
  full_name='theory.CmdFxnInput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cmdId', full_name='theory.CmdFxnInput.cmdId', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='fxnName', full_name='theory.CmdFxnInput.fxnName', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='jsonData', full_name='theory.CmdFxnInput.jsonData', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=308,
  serialized_end=371,
)


_UIDATA4ADAPTER = _descriptor.Descriptor(
  name='uiData4Adapter',
  full_name='theory.uiData4Adapter',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='adapterBufferModelId', full_name='theory.uiData4Adapter.adapterBufferModelId', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='jsonData', full_name='theory.uiData4Adapter.jsonData', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=373,
  serialized_end=437,
)


_JSONDATA = _descriptor.Descriptor(
  name='JsonData',
  full_name='theory.JsonData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='jsonData', full_name='theory.JsonData.jsonData', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=439,
  serialized_end=467,
)


_MODELLSTDATA = _descriptor.Descriptor(
  name='ModelLstData',
  full_name='theory.ModelLstData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='appName', full_name='theory.ModelLstData.appName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='modelName', full_name='theory.ModelLstData.modelName', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='jsonDataLst', full_name='theory.ModelLstData.jsonDataLst', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=469,
  serialized_end=540,
)


_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='theory.Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=542,
  serialized_end=549,
)

_REACTORREQARR.fields_by_name['reqLst'].message_type = _REACTORREQ
DESCRIPTOR.message_types_by_name['UiReq'] = _UIREQ
DESCRIPTOR.message_types_by_name['ReactorReq'] = _REACTORREQ
DESCRIPTOR.message_types_by_name['ReactorReqArr'] = _REACTORREQARR
DESCRIPTOR.message_types_by_name['UiId'] = _UIID
DESCRIPTOR.message_types_by_name['FieldData'] = _FIELDDATA
DESCRIPTOR.message_types_by_name['CmdFxnInput'] = _CMDFXNINPUT
DESCRIPTOR.message_types_by_name['uiData4Adapter'] = _UIDATA4ADAPTER
DESCRIPTOR.message_types_by_name['JsonData'] = _JSONDATA
DESCRIPTOR.message_types_by_name['ModelLstData'] = _MODELLSTDATA
DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UiReq = _reflection.GeneratedProtocolMessageType('UiReq', (_message.Message,), dict(
  DESCRIPTOR = _UIREQ,
  __module__ = 'theory_pb2'
  # @@protoc_insertion_point(class_scope:theory.UiReq)
  ))
_sym_db.RegisterMessage(UiReq)

ReactorReq = _reflection.GeneratedProtocolMessageType('ReactorReq', (_message.Message,), dict(
  DESCRIPTOR = _REACTORREQ,
  __module__ = 'theory_pb2'
  # @@protoc_insertion_point(class_scope:theory.ReactorReq)
  ))
_sym_db.RegisterMessage(ReactorReq)

ReactorReqArr = _reflection.GeneratedProtocolMessageType('ReactorReqArr', (_message.Message,), dict(
  DESCRIPTOR = _REACTORREQARR,
  __module__ = 'theory_pb2'
  # @@protoc_insertion_point(class_scope:theory.ReactorReqArr)
  ))
_sym_db.RegisterMessage(ReactorReqArr)

UiId = _reflection.GeneratedProtocolMessageType('UiId', (_message.Message,), dict(
  DESCRIPTOR = _UIID,
  __module__ = 'theory_pb2'
  # @@protoc_insertion_point(class_scope:theory.UiId)
  ))
_sym_db.RegisterMessage(UiId)

FieldData = _reflection.GeneratedProtocolMessageType('FieldData', (_message.Message,), dict(
  DESCRIPTOR = _FIELDDATA,
  __module__ = 'theory_pb2'
  # @@protoc_insertion_point(class_scope:theory.FieldData)
  ))
_sym_db.RegisterMessage(FieldData)

CmdFxnInput = _reflection.GeneratedProtocolMessageType('CmdFxnInput', (_message.Message,), dict(
  DESCRIPTOR = _CMDFXNINPUT,
  __module__ = 'theory_pb2'
  # @@protoc_insertion_point(class_scope:theory.CmdFxnInput)
  ))
_sym_db.RegisterMessage(CmdFxnInput)

uiData4Adapter = _reflection.GeneratedProtocolMessageType('uiData4Adapter', (_message.Message,), dict(
  DESCRIPTOR = _UIDATA4ADAPTER,
  __module__ = 'theory_pb2'
  # @@protoc_insertion_point(class_scope:theory.uiData4Adapter)
  ))
_sym_db.RegisterMessage(uiData4Adapter)

JsonData = _reflection.GeneratedProtocolMessageType('JsonData', (_message.Message,), dict(
  DESCRIPTOR = _JSONDATA,
  __module__ = 'theory_pb2'
  # @@protoc_insertion_point(class_scope:theory.JsonData)
  ))
_sym_db.RegisterMessage(JsonData)

ModelLstData = _reflection.GeneratedProtocolMessageType('ModelLstData', (_message.Message,), dict(
  DESCRIPTOR = _MODELLSTDATA,
  __module__ = 'theory_pb2'
  # @@protoc_insertion_point(class_scope:theory.ModelLstData)
  ))
_sym_db.RegisterMessage(ModelLstData)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), dict(
  DESCRIPTOR = _EMPTY,
  __module__ = 'theory_pb2'
  # @@protoc_insertion_point(class_scope:theory.Empty)
  ))
_sym_db.RegisterMessage(Empty)



_REACTOR = _descriptor.ServiceDescriptor(
  name='Reactor',
  full_name='theory.Reactor',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=552,
  serialized_end=945,
  methods=[
  _descriptor.MethodDescriptor(
    name='bye',
    full_name='theory.Reactor.bye',
    index=0,
    containing_service=None,
    input_type=_EMPTY,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='call',
    full_name='theory.Reactor.call',
    index=1,
    containing_service=None,
    input_type=_UIREQ,
    output_type=_REACTORREQARR,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='register',
    full_name='theory.Reactor.register',
    index=2,
    containing_service=None,
    input_type=_UIID,
    output_type=_REACTORREQARR,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='syncFormData',
    full_name='theory.Reactor.syncFormData',
    index=3,
    containing_service=None,
    input_type=_FIELDDATA,
    output_type=_JSONDATA,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='callCmdSubFxn',
    full_name='theory.Reactor.callCmdSubFxn',
    index=4,
    containing_service=None,
    input_type=_CMDFXNINPUT,
    output_type=_JSONDATA,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='adaptFromUi',
    full_name='theory.Reactor.adaptFromUi',
    index=5,
    containing_service=None,
    input_type=_UIDATA4ADAPTER,
    output_type=_JSONDATA,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='upsertModelLst',
    full_name='theory.Reactor.upsertModelLst',
    index=6,
    containing_service=None,
    input_type=_MODELLSTDATA,
    output_type=_REACTORREQARR,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_REACTOR)

DESCRIPTOR.services_by_name['Reactor'] = _REACTOR

# @@protoc_insertion_point(module_scope)
